version: '3'

services:
  database:
    build:
      context: ./docker/database
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
    ports:
      - '3307:3306'
    volumes:
      - ./docker/database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db:/var/lib/mysql

  php-fpm:
    build:
      context: ./docker/php-fpm
    depends_on:
      - database
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}  
      - DATABASE_URL=mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@database:3306/${DATABASE_NAME}?serverVersion=mariadb-10.5.5
    volumes:
      - ./:/var/www

  nginx:
    build:
      context: ./docker/nginx
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
      - ./docker/logs:/var/log
    depends_on:
      - php-fpm
    ports:
      - '86:80'
      - '445:443'

  #phpmyadmin container
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: faume_phpmyadmin2
    restart: always
    environment:
      VIRTUAL_HOST: faume.phpmyadmin.dev
    depends_on:
      - database
    ports:
      - "8099:80"
    links:
      - database
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: database
      PMA_ARBITRARY: 1
volumes:
  db: